package uz.isft.applibary.util;

import java.util.ArrayList;
import java.util.List;

public interface MessageConstants {
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
    String ADMIN_ROLE_CAN_NOT_BE_DELETED = "ADMIN_ROLE_CAN_NOT_BE_DELETED";
    String PHONE_NUMBER_SHOULD_NOT_BLANK = "PHONE_NUMBER_SHOULD_NOT_BLANK";
    String NAME_SHOULD_NOT_BLANK = "NAME_SHOULD_NOT_BLANK";
    String PASSWORD_SHOULD_NOT_BLANK = "PASSWORD_SHOULD_NOT_BLANK";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String ROLE_ID_MUST_NOT_BE_NULL = "ROLE_ID_MUST_NOT_BE_NULL";
    String THIS_NAME_ALREADY_EXISTS_IN_THIS_PARENT = "THIS_NAME_ALREADY_EXISTS_IN_THIS_PARENT";
    String UUID_CANNOT_BE_NULL = "UUID_CANNOT_BE_NULL";
    String YOU_HAVE_NOT_PERMISSION = "YOU_HAVE_NOT_PERMISSION";
    String NAME_DUPLICATE="NAME_DUPLICATE";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String DESCRIPTION_REQUIRED = "DESCRIPTION_REQUIRED";
    String MUST_HAVE_ASSIGNED_PERSON = "MUST_HAVE_ASSIGNED_PERSON";
    String ADDRESS_ALREADY_EXISTS = "This location already exists!";
    String ATTACHMENT_NOT_FOUND = "Such attachment not found!";
    String HOTEL_NOT_FOUND = "Hotel not found!";
}
